---
all: True
dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
structname: "{{ .InterfaceName }}"
filename: "mock_{{ .StructName }}.go"
packages:
  github.com/thegeeklab/renovate-operator/internal/provider:
  github.com/thegeeklab/renovate-operator/internal/frontend/auth:
    interfaces:
      AuthProvider:
  github.com/thegeeklab/renovate-operator/internal/logreader:
    interfaces:
      Reader:
