FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.4@sha256:e68f6a00e88586577fafa4d9cefad1349c2be70d21244321321c407474ff9bf2 AS build

ARG TARGETOS
ARG TARGETARCH

ENV GOCACHE=/var/cache/go
ENV GOMODCACHE=/var/cache/gomod

ADD . /workspace
WORKDIR /workspace

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN --mount=type=cache,target=/var/cache CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bin/manager cmd/renovate-operator/main.go
RUN --mount=type=cache,target=/var/cache CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bin/discovery cmd/discovery/main.go
RUN --mount=type=cache,target=/var/cache CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bin/dispatcher cmd/dispatcher/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot@sha256:e8a4044e0b4ae4257efa45fc026c0bc30ad320d43bd4c1a7d5271bd241e386d0

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="renovate-operator"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/renovate-operator"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/renovate-operator"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/renovate-operator"

WORKDIR /

COPY --from=build /workspace/bin/manager .
COPY --from=build /workspace/bin/discovery .
COPY --from=build /workspace/bin/dispatcher .

USER 65532:65532

ENTRYPOINT ["/manager"]
