# ---------------------------------------------------------
# 1. Frontend Build Stage
# ---------------------------------------------------------
FROM --platform=$BUILDPLATFORM docker.io/library/node:24-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd AS frontend-build

WORKDIR /workspace

RUN apk add --no-cache make bash

COPY . .
RUN make frontend-build GO=true

# ---------------------------------------------------------
# 2. Go Build Stage
# ---------------------------------------------------------
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.5@sha256:d52df9c279840adf958d017ebb275651ed8338b953d39817bc3633a2e6b1bbcc AS go-build

ARG TARGETOS
ARG TARGETARCH

ENV GOCACHE=/var/cache/go
ENV GOMODCACHE=/var/cache/gomod

WORKDIR /workspace
COPY . .

RUN --mount=type=cache,target=/var/cache \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} make build-go


# ---------------------------------------------------------
# 3. Final Runtime Stage
# ---------------------------------------------------------
FROM gcr.io/distroless/static:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="renovate-operator"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/renovate-operator"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/renovate-operator"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/renovate-operator"

WORKDIR /

# Copy binaries from the Go build stage
COPY --from=go-build /workspace/bin/manager .
COPY --from=go-build /workspace/bin/discovery .

# Copy the built assets from the frontend build stage
COPY --from=frontend-build /workspace/internal/frontend/static/dist ./internal/frontend/static/dist

USER 65532:65532

ENTRYPOINT ["/manager"]
