apiVersion: renovate.thegeeklab.de/v1beta1
kind: Renovator
metadata:
  name: renovator-sample-with-pullsecrets
spec:
  # Main operator image configuration
  image: my-private-registry.io/thegeeklab/renovate-operator:latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: my-registry-secret
  
  renovate:
    # Renovate bot image configuration
    image: my-private-registry.io/renovatebot/renovate:38
    imagePullPolicy: Always
    imagePullSecrets:
      - name: my-registry-secret
      - name: another-registry-secret
    
    platform:
      type: github
      endpoint: https://api.github.com
      token:
        secretKeyRef:
          name: renovator-secret
          key: github-token
    
    prHourlyLimit: 5
    
  discovery:
    schedule: "0 */2 * * *"
    filter:
      - "my-org/*"
  
  runner:
    strategy: batch
    instances: 2
    batchSize: 5
  
  schedule: "0 * * * *" 