// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

type Reader_Expecter struct {
	mock *mock.Mock
}

func (_m *Reader) EXPECT() *Reader_Expecter {
	return &Reader_Expecter{mock: &_m.Mock}
}

// ReadJobLogs provides a mock function for the type Reader
func (_mock *Reader) ReadJobLogs(ctx context.Context, namespace string, jobName string, container string, tailLines int64) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, namespace, jobName, container, tailLines)

	if len(ret) == 0 {
		panic("no return value specified for ReadJobLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, namespace, jobName, container, tailLines)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) io.ReadCloser); ok {
		r0 = returnFunc(ctx, namespace, jobName, container, tailLines)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = returnFunc(ctx, namespace, jobName, container, tailLines)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Reader_ReadJobLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadJobLogs'
type Reader_ReadJobLogs_Call struct {
	*mock.Call
}

// ReadJobLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - jobName string
//   - container string
//   - tailLines int64
func (_e *Reader_Expecter) ReadJobLogs(ctx any, namespace any, jobName any, container any, tailLines any) *Reader_ReadJobLogs_Call {
	return &Reader_ReadJobLogs_Call{Call: _e.mock.On("ReadJobLogs", ctx, namespace, jobName, container, tailLines)}
}

func (_c *Reader_ReadJobLogs_Call) Run(run func(ctx context.Context, namespace string, jobName string, container string, tailLines int64)) *Reader_ReadJobLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Reader_ReadJobLogs_Call) Return(readCloser io.ReadCloser, err error) *Reader_ReadJobLogs_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Reader_ReadJobLogs_Call) RunAndReturn(run func(ctx context.Context, namespace string, jobName string, container string, tailLines int64) (io.ReadCloser, error)) *Reader_ReadJobLogs_Call {
	_c.Call.Return(run)
	return _c
}
