---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-bootstrap
  namespace: gitea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-bootstrap-secret-manager
  namespace: renovate-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-bootstrap-secret-manager
  namespace: renovate-system
subjects:
  - kind: ServiceAccount
    name: gitea-bootstrap
    namespace: gitea
roleRef:
  kind: Role
  name: gitea-bootstrap-secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: renovate-operator-frontend-service
  namespace: renovate-system
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30882
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: renovate-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: renovate-operator-receiver-service
  namespace: renovate-system
spec:
  ports:
    - name: receiver
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: renovate-operator
