---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-operator-controller-manager
  namespace: renovate-system
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
            - --frontend-bind-address=:8082
            - --receiver-bind-address=:8083
            - --external-url=http://renovate-operator-receiver-service.renovate-system.svc.cluster.local:8083
            - --secure-cookies=false
          ports:
            - containerPort: 8083
              name: receiver
          env:
            - name: OIDC_SESSION_SECRET
              value: "dummy-session-secret"
