---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build-installer
    image: docker.io/library/golang:1.25.7
    commands:
      - make deps build-installer
      - git diff --exit-code

  - name: changelog
    image: quay.io/thegeeklab/git-sv
    commands:
      - git sv current-version
      - git sv release-notes -t ${CI_COMMIT_TAG:-next} -o CHANGELOG.md
      - cat CHANGELOG.md

  - name: publish-github
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/install.yaml
      note: CHANGELOG.md
      overwrite: true
      title: ${CI_COMMIT_TAG}
    when:
      - event: [tag]

depends_on:
  - static
  - test
