---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: golangci-lint
    image: docker.io/library/golang:1.26.0
    commands:
      - make deps golangci-lint

  - name: yaml-lint
    image: docker.io/library/golang:1.26.0
    commands:
      - make deps yamlfmt-lint

  - name: spellcheck
    image: ghcr.io/streetsidesoftware/cspell
    commands:
      - cspell-cli lint . --gitignore --color
