---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: lint
    image: docker.io/library/golang:1.25.6
    commands:
      - make deps lint

  - name: spellcheck
    image: ghcr.io/streetsidesoftware/cspell
    commands:
      - cspell-cli lint . --gitignore --color
