---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &when_locale
    - path:
        exclude: &locale_exclude_path
          - internal/frontend/i18n/locales/*.json
  - &when_golang
    - path:
        include:
          - ".woodpecker/test.yaml"
          - ".golangci.yaml"
          # go source code
          - "**/*.go"
          - "go.*"
          # tools updates
          - "Makefile"

steps:
  - name: frontend-deps
    image: docker.io/library/node:lts
    commands:
      - make frontend-deps
    when: *when_locale

  - name: eslint
    image: docker.io/library/node:lts
    depends_on: [frontend-deps]
    commands:
      - make eslint typecheck
    when: *when_locale

  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    depends_on: [frontend-deps]
    commands:
      - markdownlint 'docs/*.md' 'dist/chart/README.md' 'README.md' 'CONTRIBUTING.md'
    when: *when_locale

  - name: yaml-lint
    image: docker.io/library/golang:1.26.5
    depends_on: [frontend-deps]
    commands:
      - make yamlfmt-lint
    when: *when_locale

  - name: spellcheck
    image: docker.io/library/node:lts
    depends_on: [frontend-deps]
    commands:
      - make cspell
    when: *when_locale

  - name: golangci-lint
    image: docker.io/golangci/golangci-lint:v2.12.2
    depends_on: [frontend-deps]
    commands:
      - go mod download
      - golangci-lint run
    when: *when_golang

  - name: helm-lint
    image: quay.io/helmpack/chart-testing:v3.14.0
    depends_on: [frontend-deps]
    commands:
      - ct list-changed --target-branch ${CI_REPO_DEFAULT_BRANCH} --chart-dirs dist
      - ct lint --target-branch ${CI_REPO_DEFAULT_BRANCH} --chart-dirs dist --validate-maintainers=false --check-version-increment=false
    when: *when_locale

  - name: verify-installer
    image: docker.io/library/golang:1.26.5
    depends_on: [frontend-deps]
    commands:
      - make build-installer
      - git diff --exit-code
    when: *when_locale

  - name: format-locale
    image: docker.io/jauderho/prettier:3.9.6
    commands:
      - prettier -w internal/frontend/i18n/locales/*.json
    when:
      - path:
          include: *locale_exclude_path

  - name: verify-locale
    image: docker.io/library/golang:1.26.5
    depends_on: [format-locale]
    commands:
      - git diff --exit-code
    when:
      - path:
          include: *locale_exclude_path
