---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: eslint
    image: docker.io/library/node:lts
    depends_on: []
    commands:
      - make frontend-deps eslint
    environment:
      FORCE_COLOR: "true"

  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    depends_on: []
    commands:
      - markdownlint 'exampleSite/content/**/*.md' 'README.md' 'CONTRIBUTING.md'

  - name: yaml-lint
    image: docker.io/library/golang:1.26.2
    commands:
      - make deps yamlfmt-lint

  - name: spellcheck
    image: ghcr.io/streetsidesoftware/cspell
    commands:
      - cspell-cli lint . --gitignore --color

  - name: golangci-lint
    image: docker.io/library/golang:1.26.2
    commands:
      - make deps golangci-lint
