---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: test
    image: docker.io/library/golang:1.25.7
    commands:
      - make deps test-full
