---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: test
    image: docker.io/library/golang:1.26.4
    commands:
      - make test-ci

  - name: helm-test
    image: quay.io/thegeeklab/kube-tools
    commands:
      - make helm-test
