---
when:
  - event: [pull_request]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &when_locale
    - path:
        include:
          - internal/frontend/i18n/locales/*.json
  - &when_golang
    - path:
        include:
          - ".woodpecker/test.yaml"
          - ".golangci.yaml"
          # go source code
          - "**/*.go"
          - "go.*"
          # tools updates
          - "Makefile"

steps:
  - name: restore-go-cache
    image: quay.io/thegeeklab/wp-s3-action
    settings:
      action: [download]
      archive: True
      bucket:
        from_secret: s3_bucket_cache
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      source: ../cache/go
      target: '{{ .Repository.Slug }}/go/{{ sha256file "go.mod" "go.sum" }}.tar.gz'
      access_key:
        from_secret: s3_access_key_cache
      secret_key:
        from_secret: s3_secret_access_key_cache
    when: *when_golang

  - name: test
    image: docker.io/library/golang:1.27.1
    depends_on: [restore-go-cache]
    commands:
      - export GOCACHE="$CI_WORKSPACE/../cache/go/build"
      - export GOMODCACHE="$CI_WORKSPACE/../cache/go/mod"
      - export GOWORK=off
      - make test
    when: *when_golang

  - name: test-locale
    image: docker.io/library/golang:1.27.1
    depends_on: [restore-go-cache]
    commands:
      - export GOCACHE="$CI_WORKSPACE/../cache/go/build"
      - export GOMODCACHE="$CI_WORKSPACE/../cache/go/mod"
      - export GOWORK=off
      - make test FOCUS="Bundle|ClientJSON|SupportedLocales|Translator"
    when: *when_locale

  - name: helm-test
    image: quay.io/thegeeklab/kube-tools
    commands:
      - make helm-test
    when: *when_golang

  - name: save-go-cache
    image: quay.io/thegeeklab/wp-s3-action
    depends_on: [test]
    settings:
      action: [upload]
      archive: True
      bucket:
        from_secret: s3_bucket_cache
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      source: ../cache/go
      upload_allow_empty_source: True
      target: '{{ .Repository.Slug }}/go/{{ sha256file "go.mod" "go.sum" }}.tar.gz'
      access_key:
        from_secret: s3_access_key_cache
      secret_key:
        from_secret: s3_secret_access_key_cache
    when: *when_golang
